// let numbers =[10,20,30];
// let a,b,c =numbers;
// console.log(a);
// console.log(b);
// console.log(c);
// let data =[1,2];
// let [a =10,b=20]=data;
// console.log(a);
// console.log(b);
// let p=5;
// let q=10;
// [p,q]=[q,p];
// console.log(p);
// console.log(q);
let color =["red","green","blue"];
let[,secondColor]=color;
console.log(secondColor);